export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Safak Kocaoglu",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Janell Shrum",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Alex Durden",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    heart: 11,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    heart: 0,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    heart: 20,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout',
    date: "4 hours ago",
    userId: 4,
    like: 7,
    heart: 23,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    heart: 14,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    heart: 30,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    heart: 60,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    heart: 18,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    heart: 16,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout',
    date: "1 week ago",
    userId: 10,
    like: 104,
    heart: 19,
    comment: 12,
  },
  {
    id: 11,
    photo: "assets/post/11.jpeg",
    date: "1 day ago",
    userId: 2,
    like: 10,
    heart: 10,
    comment: 102,
  },
  {
    id: 12,
    photo: "assets/post/12.jpg",
    date: "One Min Ago",
    userId: 4,
    like: 14,
    heart: 43,
    comment: 10,
  },
  {
    id: 13,
    photo: "assets/post/13.jpg",
    date: "2 days ago",
    desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout',
    userId: 5,
    like: 105,
    heart: 23,
    comment: 15,
  },
  {
    id: 14,
    photo: "assets/post/14.jpg",
    date: "3 hours ago",
    desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout',
    userId: 9,
    like: 109,
    heart: 3,
    comment: 19,
  },
  {
    id: 15,
    photo: "assets/post/15.jpg",
    desc: 'Lion.........................',
    date: "2 week ago",
    userId: 10,
    like: 4,
    heart: 4,
    comment: 1200,
  },
  {
    id: 16,
    photo: "assets/post/16.jpg",
    date: "2 week ago",
    desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout',
    userId: 6,
    like: 200,
    heart: 6,
    comment: 300,
  },
];
